version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:rw
    command: ["./script.sh"]
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}
