version: "3.8"

networks:
  mynet:

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:rw
    command: ["./script.sh"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynet

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

volumes:
  db_data: {}
