name: Cypress Tests
on: [pull_request]
jobs:
  cypress-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .env
        run: cp .env.sample .env

      - name: Build Docker services
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 10

      - name: Populate dxcc_entities table
        run: curl "http://localhost/index.php/update/dxcc"

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npx cypress run
